### ISSUE TITLE
Allow editing of dialog messages

### ISSUE THREAD

**Issue by sitefinitysteve** [chronogolf/nativescript-store-update#14]
Afaik I don't think we can set the messages since they're hardcoded into the /src localized json files?

Could we do one of the following

- Allow us to set them in the options
- Allow us to specify a local .json file to read the strings from (or if this is possible now, just document in the readme?).  Just don't ever want to manually change anything in the node_modules folder for obvious reasons.

**Comment by jeremypele** [comment]
Hi @sitefinitysteve,

We could imagine passing the messages through the options and fallback to the i18n files if none provided 👍 

Feel free to propose a P.R if you have time :)

**Comment by sitefinitysteve** [comment]
Yeah can do, just wanted to run it by you guys to see how you'd want it handled?

**Comment by SBats** [comment]
Agree with @jeremypele to begin with we could think of passing translations in options (with a translation property containing all overridden languages)

**Comment by sitefinitysteve** [comment]
What about both, pass in direct text overrides, OR pass in an option to set the .json path so they could optionally load from a local path instead of hardcoded (just the pathing) 
https://github.com/chronogolf/nativescript-store-update/blob/master/src/helpers/locales.helper.ts#L6-L7

**Comment by sitefinitysteve** [comment]
OR... and this just occurred to me now at midnight.

Why overcomplicate, why not:
- Remove the i18n as a dependancy entirely from this plugin
- Expose setting the text through options

...now the user can just (if they need it) locally add the nativescript-i18n plugin, and pass those values into this plugins options.

**Comment by SBats** [comment]
In fact, you just made me realize I didn't update the README. For now, we removed the i18n plugin as we weren't able to make it work with our plugin. So yeah don't put i18n as a dependency and the user can pass translations to the plugin through the config as he/she wish.
(Could be a js object, a require of a custom json file, or i18n values).

**Comment by sitefinitysteve** [comment]
Great, I'm on it :)

**Comment by SBats** [comment]
Closed by #16
