### ISSUE TITLE
Will this plugin work for versioning style MAJOR.MINOR.PATCH?

### ISSUE THREAD

**Issue by shiv19** [chronogolf/nativescript-store-update#17]
The app I'm working on uses MAJOR.MINOR.PATCH,
there is no REVISION version.
Will this plugin work with that?

**Comment by SBats** [comment]
Hi @shiv19, actually the REVISION version is inferred from the BUILD number of the NS app. We might want to change its name in the doc or clarify this.

**Comment by shiv19** [comment]
Hi @SBats, thanks for clearing that for me 👍
