### ISSUE TITLE
Q: Can notifyNbDaysAfterRelease be set to 0?

### ISSUE THREAD

**Issue by shiv19** [chronogolf/nativescript-store-update#18]
I want the user to get notified of the update as soon as possible,
is it allowed to set notifyNbDaysAfterRelease to 0?

**Comment by jeremypele** [comment]
Hi,

you can set the value to 0, nothing prevents that.
Default is 1 day because that's a good practice when using store APIs, as there's almost always a 1-day delay between what the API returns and the actual update of the application on the store.

It's your call :)

**Comment by shiv19** [comment]
@jeremypele Thanks! :)
